# Default test configuration
---
Label:
  "Resource n":
    - "N95 Surgical"
    - "ASTM Mask"
    - "Non procedural Mask"
    - "Cloth Mask"
    - "Gloves"
  Population_p:
    - "Healthcare Workers"
    - "Non-Heathcare Worker"
  Level_l:
    - Essential
    - Non-essential
  Demand_m:
    - WA0
    - WA1
    - WA2
    - WA3
    - WA4
    - WA5
    - WA6
  "Res Attributes a":
    - Units
    - Volume
  "Pop Details d":
    - Size
    - Cases

# http://yaml4r.sourceforge.net/doc/page/collections_in_yaml.htm
# https://pyyaml.org/wiki/PyYAMLDocumentation
Resource:
  res_attr_pa:
    - - 1
      - 3
      - 1.5
    - - 1
      - 2
      - 0.7
