# Default test configuration
---
Label:
  "Resource n":
    - "N95 Surgical"
    - "ASTM Mask"
    - "Non procedural Mask"
    - "Cloth Mask"
    - "Gloves"
  "Population p":
    - "Healthcare Workers"
    - "Non-Heathcare Worker"
  "Pop Level l":
    - Essential
    - Non-essential
  "Demand m":
    - WA0
    - WA1
    - WA2
    - WA3
    - WA4
    - WA5
    - WA6
  "Res Attribute a":
    - Units
    - Volume
  "Pop Detail d":
    - Size
    - Cases
  "Res Safety Stock s":
    - High
    - Mid
    - Low

# http://yaml4r.sourceforge.net/doc/page/collections_in_yaml.htm
# https://pyyaml.org/wiki/PyYAMLDocumentation
Resource:
  res_attr_pa:
    - - 1
      - 3
      - 1.5
    - - 1
      - 2
      - 0.7
