Label: 
  4   "Resource n":
  5   ¦ - "N95 Surgical"
  6   ¦ - "ASTM Mask"
  7   ¦ - "Non procedural Mask"
  8   ¦ - "Cloth Mask"
  9   ¦ - "Gloves"
 10   "Population p":
 11   ¦ - "Healthcare Workers"
 12   ¦ - "Non-Heathcare Worker"
 13   "Pop Level l":
 14   ¦ - Essential
 15   ¦ - Non-essential
 16   "Demand m":
 17   ¦ - WA0
 18   ¦ - WA1
 19   ¦ - WA2
 20   ¦ - WA3
 21   ¦ - WA4
 22   ¦ - WA5
 23   ¦ - WA6
 24   "Res Attribute a":
 25   ¦ - Units
 26   ¦ - Volume
 27   "Pop Detail d":
 28   ¦ - Size
 29   ¦ - Cases
 30   "Res Safety Stock s":
 31   ¦ - High
 32   ¦ - Mid
 33   ¦ - Low
# Default test configuration
---
Label:
  "Resource n":
    - "N95 Surgical"
    - "ASTM Mask"
    - "Non procedural Mask"
    - "Cloth Mask"
    - "Gloves"
  "Population p":
    - "Healthcare Workers"
    - "Non-Heathcare Worker"
  "Pop Level l":
    - Essential
    - Non-essential
  "Demand m":
    - WA0
    - WA1
    - WA2
    - WA3
    - WA4
    - WA5
    - WA6
  "Res Attribute a":
    - Units
    - Volume
  "Pop Detail d":
    - Size
    - Cases
  "Res Safety Stock s":
    - High
    - Mid
    - Low

# http://yaml4r.sourceforge.net/doc/page/collections_in_yaml.htm
# https://pyyaml.org/wiki/PyYAMLDocumentation
Resource:
  res_attr_pa:
    - - 1
      - 3
      - 1.5
    - - 1
      - 2
      - 0.7
