# Dimensions the model
# Note each of these yaml files has an overall label, so you can copy and concat
# as needed
Label:
  "Resource n":
    - "N95 Surgical"
    - "ASTM Mask"
    - "Non procedural Mask"
    - "Cloth Mask"
    - "Gloves"
  "Population p":
    - "Healthcare Workers"
    - "Non-Heathcare Worker"
  "Pop Level l":
    - Essential
    - Non-essential
  "Protection m":
    - WA0
    - WA1
    - WA2
    - WA3
    - WA4
    - WA5
    - WA6
  "Res Attribute a":
    - Units
    - Volume
  "Pop Detail d":
    - Size
    - Cases
  "Res Safety Stock s":
    - High
    - Mid
    - Low
