# The base dictionary data
---
Data:
  "Population p":
    "Pop Detail Data pd":
      Size:
        - 735.2
        - 7179.6
    "Protection pm":
      - [0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5]
      - [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    "Pop to Level pl":
      - [1, 0]
      - [0, 1]
  "Demand m":
    "Level to Resource mn":
      - [0, 0, 0, 0, 0, 0, 0, 0, 0]
      - [0, 0, 0, 0, 0, 2, 3, 4, 12]
      - [0, 0, 0, 0, 1.1, 3, 1, 3, 02]
      - [0, 0, 0.1, 3, 5, 6, 7, 8, 3]
      - [0, 2, 3, 4, 5, 6, 0.2, 4, 2]
      - [0.3, 6, 1, 3, 4, 5, 6, 7, 2]
      - [1.18, 0, 4, 6, 7, 1, 3, 7, 1]
  "Resource n":
    "Res Attr Data na":
      - [1, 2, 0.7]
      - [1, 1.5, 0.8]
      - [1, 4, 0.9]
      - [1, 2, 3]
      - [1, 2.3, 0.7]
      - [1, 2, 1]
      - [1, 1, 0.5]
      - [1, 0.9, 0.7]
      - [1, 2, 2]
    "Pop Level Res Cost ln":
      - [3, 4.5, 2, 4, 2, 1, 3.9, 2.3, 1.1]
      - [0.5, 0.75, 0.8, 1, 0.9, 1.2, 0.7, 1.2, 1.14]
    "Res Inventory Initial ln":
      - [1, 2, 3, 4, 5, 6, 7, 8, 9]
      - [10, 20, 30, 40, 50, 60, 70, 80, 90]
    "Res Inventory EOC ln":
      - [101, 200, 300, 400, 500, 600, 700, 800, 900]
      - [102, 201, 301, 401, 501, 601, 701, 801, 901]
    "Res Inventory Min ln":
      - [201, 300, 500, 700, 900, 1001, 2003, 2004, 2006]
      - [200, 400, 600, 800, 1000, 2001, 2002, 2005, 2007]
    "Res Inventory Min in Periods ln":
      - [30, 15, 15, 15, 25, 20, 30, 15, 20]
      - [30, 15, 15, 15, 25, 20, 30, 15, 20]
