# Dimensions the model
# Note each of these yaml files has an overall label, so you can copy and concat
# as needed
---
Label:
  "Resource n":
    - "Level"
    - "N95 + Mask"
    - "N95"
    - "ASTM 3 Mask"
    - "ASTM 1-2 Mask"
    - "Non ASTM Mask"
    - "Face Shield"
    - "Gowns"
    - "Gloves"
    - "Shoe Covers"
  "Population p":
    - "Healthcare Workers"
    - "Non-Heathcare Worker"
  "Pop Detail d":
    - Size
  "Pop Level l":
    - Essential
    - Non-essential
  "Consumption m":
    - WA0
    - WA1
    - WA2
    - WA3
    - WA4
    - WA5
    - WA6
  "Res Attribute a":
    - Units
    - Volume
    - Area
  "Res Safety Stock s":
    - High
    - Mid
    - Low
