---
Config:
  modules: 7
  dashboard: true
  stockpile: 30
  stockpile_high: 90

# Note each of these yaml files has an overall label, so you can copy and concat
# as needed
Dimension:
  "Resource (n)":
    - "N95 Surgical"
    - "N95 Non-surgical"
    - "ASTM 3 Mask"
    - "ASTM 1-2 Mask"
    - "Non ASTM Mask"
    - "Face Shield"
    - "Gowns"
    - "Gloves"
    - "Shoe Covers"
  "Resource Attribute (N)":
    - Units
    - Volume
    - Area
  "Population (p)":
    - "Healthcare Workers"
    - "Non-Heathcare Worker"
  "Population Attribute (P)":
    - Size
    - Sick
    - Diabetes
  "Population Summary Level 1 (p1)":
    - Essential
    - Non-essential
  "Organization (o)":
    - Hospital
    - "Rural EMT"
  "Organization Attribute (O)":
    - Employees
    - Patients
    - "ICU Patients"
    - Runs
  "Organization Summary Level (o1)":
    - Front-line
    - Essential
    - Non-essential
  "Demand for Resource (d)":
    - WA0
    - WA1
    - WA2
    - WA3
    - WA4
    - WA5
    - WA6
  # Owner of the warehouse only hold the State for now
  "Inventory (i)":
    - State
  # Inventory attributes typically these are over different Resources
  # So iIR will be typical so for instance State Backstop i=State
  # might have N95 Surgical and ASTM 3 Masks in stock r=Resources
  # And then each will have inventory parameters I
  "Inventory (I)":
    - Initial
    - EOQ
    - Minimum
  "Warehouse (w)":
    - Tukwila
  "Warehouse Attribute (W)":
    - Area
    - Capacity
  "Range (r)":
    - High
    - Mid
    - Low
  "Geographical Location (g)":
    - County
    - State
    - Country
  "Time (t)":
    - 0
    - 1
    - 2
    - 3

# Uses the dimensions above to create matrices
Model:
  population_pP_tr:
    name: "Population Attributes (p->P:tr)"
    description: |
      There are p Populations in the model and each population
      can have P attributes about them such as their degree of age,
      ethnicity, attitudes and awareness behaviors. The first attribute is
      the size of the sub-population. It models a real entity.
    units: Total
    kind: Real
    # The dimensinos for each
    dimension:
      - "Population (p)"
      - "Population Attribute (P)"
    # note the data can be an array, or a file pointer
    array:
      - [735.2, 0, 12]
      - [7179.6, 74, 234]

  pop_demand_per_unit_map_pd_um:
    name: "Per Unit Demand by Population for Resources (p->d:um)"
    description: |
      For each p Populations falls into which protection
      category for the burn rate. That is what does each population p need
      of each resource r.  For example, 1.18 would mean you need 1.18 N95
      masks per day for a given population
    units: "Per Person"
    kind: Map
    dimension:
      - "Population (p)"
      - "Demand for Resource (d)"
    array:
      - [0.0, 0.0, 0.0, 0.0, 0.0, 0.5, 0.5]
      - [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]

  pop_to_popsum1_per_unit_map_pp1_us:
    name: "Population to Population Level 1 Summary Map (p->p1:us)"
    description: |
      This maps every population p into any number of summary levels p1
      summarized by the p1 Level level used. In this model higher
      levels mean more protection by convention, but that isn't necessary.
      You can also a given population row spread across different levels
      so that for instance a percentage of a population could go into
      different rows
    units: "Per Person"
    kind: "Summary"
    dimension:
      - "Population (p)"
      - "Population Summary Level 1 (p1)"
    array:
      - [1, 0]
      - [0, 1]

  organization_oO_tr:
    name: "Organization Attributes (o->O:tr)"
    description: |
      For p Organizations we are modeling there are O attributes
      for each. For example an attribute might be how many
      employees or how many patients that have if the are a hospital
    units: "Total"
    kind: Real
    dimension:
      - "Organization (o)"
      - "Organization Attribute (O)"
    array:
      - [437, 21, 1, 0]
      - [58, 0, 0, 10]

  demand_per_unit_map_dn_um:
    name: "Demand Level for Resource Per Unit Map (d->n:um)"
    description: |
      Demand levels for a given population for resources. This is the
      consumption map that for each protection level shows which resources are
      "burned".  Also now as the burn rates for PPE.
    units: "Per Resource"
    dimension:
      - "Demand Level (d)"
      - "Resource (n)"
    array:
      - [0, 0, 0, 0, 0, 0, 0, 0, 0]
      # Resident or patient
      - [0, 0, 0, 0, 1, 0.02, 0.01, 0.5, 0]
      # Office worker
      - [0, 0, 0, 0, 2, 0.04, 0.02, 1, 0]
      # Customer facing worker (teacher)
      - [0, 0, 0, 1, 2, 0.08, 0.03, 2, 0.05]
      # Blue collar
      - [0, 0.05, 1, 0, 3, 0.12, 0.05, 4, 0.2]
      # Lab and other likely contact
      - [0, 1, 2, 1, 0, 0.18, 1.5, 8, 0.4]
      # Healthcare with direct contact
      - [1.18, 0, 4.03, 1, 0.05, 0.27, 3.65, 12, 0.6]

  resource_nN_ur:
    name: "Resources Attributes (n->N:ur)"
    description: |
        For all n Resources, these are the figures for each of the N Attribute
        of each resource.
    array:
      - [1, 2, 0.7]
      - [1, 1.5, 0.8]
      - [1, 4, 0.9]
      - [1, 2, 3]
      - [1, 2.3, 0.7]
      - [1, 2, 1]
      - [1, 1, 0.5]
      - [1, 0.9, 0.7]
      - [1, 2, 2]

  res_by_popsum1_cost_per_unit_p1n_us:
    name: "Cost of Resources by Population Summary Level 1 (p1->n:us)"
    description: |
      For each of p1 summary levels, get the per capita cost for each of n
      Resources.
    data:
      - [5.0, 4.0, 1.0, 0.60, 0.20, 2.50, 4.0, 0.20, 0.15]
      - [5.0, 4.0, 1.0, 0.60, 0.06, 1.50, 4.0, 0.20, 0.15]

  inv_by_popsum1_parameters_ip1n_tp:
    name: |
      "Inventory of Resources by Population Summary Level 1 Parameters (p1n:tr)"
    description: |
      For each summarized population level l, this gives for every resource n
      initial inventory. The first plane is the initial inventory, the
      second plane is the economic order quantity and the initial inventory,
      third plane is the minimum safety stock.
    dimension:
      - "Inventory (i)"
      - "Population Summary Level 1 (p1)"
      - "Resource (n)"
    unit: "Total Units"
    kind: Real
    array:
      -
        - [201, 300, 500, 700, 900, 1001, 2003, 2004, 2006]
        - [200, 400, 600, 800, 1000, 2001, 2002, 2005, 2007]
      -
        - [1, 2, 3, 4, 5, 6, 7, 8, 9]
        - [10, 20, 30, 40, 50, 60, 70, 80, 90]
      -
        - [101, 200, 300, 400, 500, 600, 700, 800, 900]
        - [102, 201, 301, 401, 501, 601, 701, 801, 901]

# These tables are generated from the inputs above so they are derited values
# These are typicalally meta values that are derived from real objectcs
# And mapps that sever as input to processes
Description:
  pop_demand_per_person_pn_uc:
    name: "Per Capita Population Resource Demand (pn:uc)"
    description: |
      This is the per capita demand for a give population so this is not the per
      capita demand but for every n Resource for ever subpopulation p
    dimension:
      - "Population (p)"
      - "Resource (n)"
    units: "Per Capita"
    kind: Calculated

  popsum1_demand_per_person_p0n_uc:
    name: "Demand for Resources by Population Summary Level 1 (p1n:uc)"
    description: |
      This is the per capita demand for a set of n resources
      summarized by the l Summary Level used. It provides a view of demand
      aggregated by the summary level.
    units: "Per Capita"
    kind: Calculated
    dimensions:
      - "Population Summary (p1)"
      - "Resource (n)"

  pop_demand_total_pn_tc:
    name: "Total Demand for Resources of all Populations (pn:tc)"
    description: |
      This is the total demand for all p sub-Population for every resource n
    units: Total
    kind: Calculated
    dimensions:
      - "Population (p)"
      - "Resource (n)"

  popsum1_demand_total_p1n_tc:
    name: "Total Resource Demand by Population Summary Level 1 (p1n:tc)"
    description: |
      For all population summary levels p1, the total demand for a set
      of n resources
    units: Total
    kind: Calculated
    dimensions:
      - "Population Summary Level 1 (p1)"
      - "Resource (n)"

  popsum1_demand_total_cost_p1n_xc:
    name:
      "Total Cost of Resource Demand by Population Summary Level 1 (p1n:xc)"
    description: |
      For all population summary levels (p1), the total cost for a set of
      n resources
    units: "Total Cost"
    kind: Calculated
    dimensions:
      - "Population Summary Level 1 (p1)"
      - "Resource (n)"

  inv_popsum1_ip1n_tc:
    name: |
      "Total Inventory by Population Summary of Resources (wp1n_tc)"
    units: "Total Units"
    kind: Calculated
    dimensions:
      - "Inventory (i)"
      - "Population Summary 1 (p1)"
      - "Resource (n)"

Paths:
  Root: '../../data/ingestion/'
  OES: 'all_data_M_2019.xlsx'
  CODE: 'list1_2020.xls'
  POP: 'co-est2019-alldata.csv'
  MAP: 'covid-surge-who.xlsx'
