name: restart
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - scipy
  - pre-commit
  - pip
  - pip:
    - altair
    - pyyaml
    - xlrd
    - tables
    - confuse
    - setuptools
    - wheel
    - twine
    - voila
    - ipywidgets
    - ipysheet
    - bqplot
    - ipympl
    - ipyvolume
    - ipyvuetify
    - voila-vuetify
    - nptyping
    - pydocstyle
    - pdoc3
    - flake8
    - mypy
    - bandit
    - black
    - tox
    - pytest
    - pytest-cov
    - pytest-xdist
    - tox
    - yamllint
    - isort
    - seed-isort-config
    - jupyter-server==0.1.1
