---
name: Format

on: push

jobs:

  format:

    runs-on: ubuntu-latest

    steps:

    # checkout repo under $GITHUB_WORKSPACE
    - name: Checkout action
      uses: actions/checkout@v2
      with:
        lfs: true

    # install latest python version
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Force formatting with isort
      run: |
        pip install isort
        isort --profile=black -w 79 $(find ./restart -name "*.py")

    - name: Force formatting with black
      run: |
        pip install black
        black -l 79 $(find ./restart/ -name "*.py")

    - name: Commit changes
      run: |
        git checkout ${GITHUB_REF##*/}
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A && git diff-index --cached --quiet HEAD || git commit -m 'automatic formatting'

    - name: Push changes
      run: |
        git checkout ${GITHUB_REF##*/}
        git push
