# This is a basic workflow to help you get started with Actions
# https://github.com/actions/upload-release-asset

name: Release Upload

# Only run when a release is created
on:
  release:
    types:
      - created
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    # Also need git lfs
    steps:
    - name: Checkout release
      uses: actions/checkout@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # only checkout what you need
    - name: Checkout LFS Objects
      # https://git-scm.com/book/en/v2/Git-Basics-Tagging
      run: git lfs pull --include "covid-surge-who-1.3.1.xlsx"
    - name: Checkout LFS Objects
      # Note do not check all the object out there are a huge number
      run: git lfs checkout covid-surge-who-1.3.1.xlsx
    - name: Upload release
      uses: actions/upload-release-asset@v1.0.2
      with: 
        # The URL for uploading assets to the release so this won't work if
        # there is no release
        upload_url: ${{ github.event.release.upload_url }}
        # The path to the asset you want to upload
        asset_path: ./covid-surge-who-1.3.1.xlsx
        # The name of the asset you want to upload
        asset_name: covid-surge-projection-${{ github.event.release.tag_name }}.xlsx
        # The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information
        asset_content_type: application/zip

